name: CWA Coastal Wave and Risk Forecast

on:
  schedule:
    - cron: '0 22 * * *'  # 每天 UTC 22:00（台灣時間早上6點）
  workflow_dispatch:  # 允許手動觸發

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # 不使用 Git LFS

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgdal-dev libgeos-dev libproj-dev
        sudo apt-get install -y fonts-noto-cjk

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run visualization script
      env:
        CWA_API_KEY: ${{ secrets.CWA_API_KEY }}
      run: python CWA_Waverisk.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./images
