name: CWA Coastal Wave and Risk Forecast

on:
  schedule:
    - cron: '0 22 * * *'  # 每天 UTC 22:00（台灣時間早上6點）
  workflow_dispatch:  # 允許手動觸發

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgdal-dev libgeos-dev libproj-dev
        sudo apt-get install -y fonts-noto-cjk fonts-noto-cjk-extra
        # 下載 Noto Sans TC 作為備用
        wget https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSansTC/NotoSansTC-Regular.otf -P /usr/share/fonts/truetype/noto/ || echo "Failed to download NotoSansTC-Regular.otf"
        # 清理 matplotlib 字型快取
        rm -rf ~/.cache/matplotlib
        # 更新系統字型快取並列出所有字型
        fc-cache -fv
        fc-list | grep "Noto Sans" || echo "No Noto Sans fonts found"
        # 檢查字型檔案
        ls -l /usr/share/fonts/truetype/noto/ | grep "NotoSans" || echo "No NotoSans fonts found"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run visualization script
      env:
        CWA_API_KEY: ${{ secrets.CWA_API_KEY }}
      run: python CWA_Waverisk.py

    - name: Commit and push images to main branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add images/*
        git commit -m "Add generated wave risk charts to images/ directory" || echo "No changes to commit"
        git push origin main
